#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>ON COMPUTER - View 3D Image Only:</b> <br>
    Use Pointer to rotate, spin; Use zoom to scale
  <br><br> 
  <b>ON MOBILE - View in Augmented Reality (AR):</b> <br>
    <b><u>STEP 1</u></b>- Scroll down press AR button, place image in open space, anchor on surface, scale & tour apartment  
  <br><br>
  <a href="https://avertek.net/xr-now-apartments"><b><u>STEP 2</u></b>- View Actual Apartment Images</a> 
  <br><br>
  <a href="https://avertek.net/narrative"><b><u>STEP 3</u></b>- Take a Video Tour/Testimonials</a>
  <br><br>
  <a href="https://avertek.net/contact-us"><b><u>STEP 4</u></b>- Contact Us for a Personal Tour; Receive a Free Gift</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
